### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by henrihallik** [echonest/echoprint-ios-sample#2]
Hi, I am trying to compile the iOS example and have following issues:

ld: warning: directory not found for option '-L/Users/Yrgel/Desktop/echonest-echoprint-ios-sample-b937c04/../../echoprint-codegen/src/echoprint-codegen-ios/build/Release-iphoneos'
Undefined symbols for architecture armv6:
  "_vDSP_vsmul", referenced from:
      Spectrogram::SimpleFFT(float_&) in libechoprint-codegen-ios.a(Spectrogram.o)
  "_vDSP_destroy_fftsetup", referenced from:
      Spectrogram::~Spectrogram()in libechoprint-codegen-ios.a(Spectrogram.o)
      Spectrogram::~Spectrogram()in libechoprint-codegen-ios.a(Spectrogram.o)
  "_vDSP_create_fftsetup", referenced from:
      Spectrogram::Init()      in libechoprint-codegen-ios.a(Spectrogram.o)
  "_vDSP_ctoz", referenced from:
      Spectrogram::SimpleFFT(float_&) in libechoprint-codegen-ios.a(Spectrogram.o)
  "_vDSP_fft_zrip", referenced from:
      Spectrogram::SimpleFFT(float*&) in libechoprint-codegen-ios.a(Spectrogram.o)
ld: symbol(s) not found for architecture armv6
collect2: ld returned 1 exit status

Can anybody please tell me how to fix this?

**Comment by henrihallik** [comment]
Installed the boost, taglib and ffmpeg properly with brew and check out the code from scratch and was able to compile it.

**Comment by etiksan** [comment]
I'm getting same errors all the time. also installed taglib, boost and ffmpeg with brew but nothing changed. have you done anything more ?

**Comment by TimKreger** [comment]
I had the same errors. It required adding the Accelerate framework. Those symbols belong to Veclib. Not sure how anyone else got this to compile without it?
