### ISSUE TITLE
Why iOS not recoqnize anything?

### ISSUE THREAD

**Issue by henrihallik** [echonest/echoprint-ios-sample#3]
Hi,

i compiled the iOS example app, tried to use microphone input. tried it with various song and always got no match.

the response is

2011-08-20 17:25:02.187 echoprint[8592:707] {
    response =     {
        songs =         (
        );
        status =         {
            code = 0;
            message = Success;
            version = "4.2";
        };
    };
}

does it recoqnize any songs at all?
what songs should i try?

**Comment by henrihallik** [comment]
Please can anybody tell me what I am doing wrong and what songs should i try?

**Comment by vokilam** [comment]
same story, no results. tried to choose song and record microphone input

**Comment by tjehan** [comment]
echoprint is still being setup. Notably, at the moment, the backend doesn't have many song and won't until we ingest a large catalog from a partner. Visit http://echoprint.me/ for more info and stay tuned.

**Comment by henrihallik** [comment]
thanks, but which songs could we try atm?

**Comment by tjehan** [comment]
Sorry I don't have the list. Please for service-related discussions, use the forum. http://groups.google.com/group/echoprint?hl=en Thanks.

**Comment by digitalDeveloper** [comment]
Has anyone found a few songs with which the app works?

**Comment by keertimaan** [comment]
I am also experiencing the same issue. I just downloaded the sample ios echoprint example from github and tried with multiple songs including "Billy Jean" but i am always getting the success code with empty artist array. I am also appending the version=4.11 to the url. Could someone help me to fix this.

Here is the code for one of the song which i tried,

eJzFmQluHrkOhK-kjSJ1HK33P8L72MbLPzDQMjBGMEBQcXpRS2SxWHRCCKGFC8Rzg1xvUOYN6rpBazcY4wZbLxBjvoEv_w4nXSB5SN7h7AvkXG4g9QaWLlBiuYEn6hVCsBtkucE9-9f8xtBvEPcNVG9g6wZ7XyB5wN4hjRvkeQNNN1jxAtnJ9Q4rX-CH2v8hv-MGP1SoXSCGdoN79u0KjwC8QXIBeAe1G1xzlM66QPbl3-EqsXnPC_xO26_Zr-kGdm5w54ar_ytEL7V3KPEG3lje4Tfa3uUGP3Dj2hdEb2D5Bh7NVyiexlf4m67gqht_j1fz3OCuSFFucGfd1BucfIFfMeeuKndueJt9hR9cgcvwO9y5UfMN_rPs_zXN6Tf4QXN-1Y-uzOnnAj_l9xee4V77fqx38Pb-Dv0K3oRf4YcMutC-Qy83OO0CP2TfA_YOvvw77Bv8MGvoDYoLwDv8quP8gnU_9JR_z5yflCHc4O8pw50bv9GNLRf499woaVgMq5-1dh1Zk0btKku4V3W13SRLyy3s0fqOaaxcy1otrrqKnXLOKkPTSs3G6bLSCiftHbWuuqnEnlffdWazFmXijGOrPDSe9T5LxXL4djinx6hxPe-mCIeeu3mXOHQE3TnnPpOQihxazq31ZqzOHlPsuumvtTasARNJLrMKs7TfLeYyt46R4cYHzixHzth4iM7jfdIwxkq758j-V0-qurWsbGEXjKS1s9J4Fg3GT7rWkjrZoehMe3bOO8axcPYU4_u7B_9ItyTLsp1hRZIRz5746krHeKymeaIW0a_z7jmGbm-3xfTMlXWsOldIgc2MnU6UzLtf21ilnTSbBJ11U4m9FJyn6hKzGuFEJ6cctO3Y1hStJ7Sd50Bo_gHtSLdv1z4wVcKxOVpeI2_lLHl2xrW4B6RsrbD7WrtEFWknVGFHqeaGQW4e8j5G3TOWUkvgPLaGxmy1RCmSx1biuEvqMVkwUfHft5Qd45BUiFw8HbqYzo4KtcEoTwCHJSvYijKXSt3oxGwlEMA9clCnmEchtBOPVOladeqx3VY-MZKpJTsY43mx4v-yPusgNMeUjVvKcHnMk5tAu3xED5btpDFXK1Uksp_TcSbGQmRkhA6Z85ZpHG3b2lZl6SlhccbRZvUM7TIO8aejwfuZ-uZCPHYmsT095VpTb5QQPJcMnYlrCzpSS3WvFbOKxlrZWBsn85IzMxCt2YUK1JNKgilxzrJHhOf_AJFc87drH8gx5bEUdrJ3iDQ4ADlFEEYNtVTyVxCDWDxqg2Mla9OokSG97LMbvCqcM53Z2d96hrXCY2fORm0nFkEh4LCm0icXN1Ss6iKTKH3x37HsvPtoZZHalddEgfmrnSnIqZbBR0qnWor0M4gidaox8IOEuZOQA0ULeH95wqeMZtpDPqPDzMFeDdmyDQ-JJmqocba-YkyHNsJGt2-ZSAuFOaQoRmtZ6Zy_KfWR5JBWsV5l68gVbpecqMBhdbewGiGCOYcTFBnkFyKnGisOtFajdGd2_vHxyXLdFDEYPMKY2JGOPSGjqpfa014W31ZrNRdiXaKVtmHwINsjkI-YeGCcD4SCLn279oFUzkRiYH5ENRdng3xnLNQ3yzC0gb0VBGqggChZ6ShqtYEX2c8bz8No0T6oS8DARN3Ccb_WO72hxSzWCnpEpsjyrpHsDm1lc3Iij74_dxdyF8Rqb8JrbZUe0rONsqaV2lJfz93ioxmMIv67wf3sFdAM3YmTwD_ngKAyo9D5BOHtXOSTEYPlH0KWG1TUZii59wvL1HdE6Xz5ZD0lrsAnJID1F_LrMvS8-6wMA-RrZWuGACaE5XkXkVqBCNl5VuFVZCEPoahpICtVlScGzw7S3Pk8S8GCvVlloaNzOP0GZb6RSb_7xGAHGsTzjdbVp6K497PJz3mf9Z5dcXRtlZ4QPnt-ziuJ3PjHO6K42rPenDHQMg4q1g0N-gCas79f-wOon-qBI5tGmMsWI0DkPUWbDSczYQCc5cqkVWZaKUKDRlM33osNvZjsM1AlaWIAzDCax9Ju1FxpkxZX-BRCZzIL_cVgJxx5vqGnNR2oOp0L7naSQHyDHKVk5VkUxlIdvmivG0UvgXRPBGWitLZHmigUUsty3mlSW9RxgJtZY2dhWnRZFXajpmSV9llRjsLhgpkxiSP9WFTBtHgPJwT63E20E7qvzkJXcP0fe3sDxe2wvxT8sJT6193kykcTJBQnFqVeaEJ88vAjwzw8jEINHqv1KFKF-8CN0YsGoaUJVqI8-_NdQSXwDnV1l4lTxUan38Jz-g0WqdB5TiX0Lt654-o2si2NEXtXm4k18DFB0GmrNJwnJAh_hnmkC21mPvkD_nvz9u3aB3LCDZ4-rOPfjFTTy9bgu3FJPIQ3s0H6SydxCOzCrKC8xrZjgQ78MyJP3Xm5Js_SFWAOVqILHSIVnEaQyotz1lSxqVYX5b9xhg3uVIIyM1oyuANPa38eqVgE5LshvY2Wf1JEMP4sEPBmGpBLzIf_cgc7Opq205DyIM8b-AD5eviQhoUZW4ZY9_nc5VhsGIezinpHZyLbJ9BsiBQ27FCzB79HClco01tIDgSXSsDN4kVgbd4kDKXazrwIydETwtYxgwwAHT-bUoRhgaamOQ8XyHx4VVprmQaaB-uXTKzs_3FBoCtGC9GmMr0Bu4057saO_2cebgNjYBHvFtH26J1sRnaOJBq2EO1CkpCesz-QEmb727UPcCxcf_FHaMtKO0ejU1qZdOgZaJwpuk9Y6Sy1RrGvu3kGOkYM8-vuWil5r_ecxkFPRMAtEoCUzxLCSs_07kiEiI0oVU2nUGofeTysh9FzX8awzxvDKGnqZeJFJkaareK2IJehF4No5JWRihMn1iY8JcX8kQdaRui2tjUoWlR_VaHs2QhVCzdIEbYG9wCnQw6ECwPTI-3SD4pIa2CzNNWJAcTaYrXCcxAmKWTNtcJ7OxMr7Z2OTv_oubEzvKsHDuVMo_tpcWrYudRp5tJHrW6QGkMBcyN9CKMw0BWazkGY8WgMJiYVW8Z4VodgEio6N5aPEqtXTE_DopaGbMNkIYorti54F10EkLTTl2btWOxMmDauDQ4qPNOKLmFj-QNNqarAoISdmZKgDP4qu03UhnNFeKd7hhQf740N3d2rZuDTeQ7zh2H6wBI559u1DyAoWBzcAjGeVBEjz8QV4PQwI7vQT-ndlGwym7gpZseie0XXufm8gUnCLB13VYqgM0ZiiyEZ80-d-H2ex0DiPL15LEbRsl084UDpiIb6XIWecWgaiUtBhrYu_0wXIU-cXFXKhhml0yPTQm-f79ZIZxaMdFl4MSQb3ZGaEGH3L89eEDydz13z_3Xqi9HOad_hDCTybUC0sc9xJ-Z3afvV-yF5Qh0wAx2p1g3XrY2v8z4nwuGl03yCYW89-tTDNaZaLBAbxke7jWExOgcGLjWWChCPuV6YazPFxqgnnYkq8qmnC6Kc-AxcWEE6OsyghSK4x4Xeqe6ilRHgqYxlJJVqnRvD_kSI-LdTvWInhWEfeLb77doH_gdDLjF9
