### ISSUE TITLE
How to interpret the Hash Code

### ISSUE THREAD

**Issue by digitalDeveloper** [echonest/echoprint-ios-sample#6]
Hi, i'm working on iPhone app and i want ask if there are a way for interpret the Hash Code result after the recording.
How can i  retrive information about frequency and timestamp ?

**Comment by bwhitman** [comment]
look at fp.py in echoprint-server

**Comment by digitalDeveloper** [comment]
I've read that the code generated is a base64 code, but i can find also '_' characters, so how can i decode the result code?

**Comment by bwhitman** [comment]
please look at fp.py in echoprint-server. all your questions are answered there.

**Comment by digitalDeveloper** [comment]
Sorry but i've looked at fp.py but python is not my language and i can't understad how decode the base 64 string  
I think that the decoder used in this code convert also '_' character... i'm wrong??

**Comment by ddesroches** [comment]
The codestring is base64 encoded with "file/url safe" syntax, so underscore '_' is used instead of slash '/' and dash '-' instead of plus '+'. See http://www.doughellmann.com/PyMOTW/base64/ for a good description of this (for Python).
